### ISSUE TITLE
Implement 10-parameter HOD or AbacusHOD

### ISSUE THREAD

**Issue by maho3** [maho3/ltu-cmass#63]
The goal here is to add functionality to `cmass.bias.apply_hod` to allow for additional, more complex HOD. Such as:

- A SimBIG-eque 10-parameter HOD, including a controller for assembly bias: https://arxiv.org/abs/2211.00660
- AbacusHOD : https://arxiv.org/abs/2110.11412

These HODs might require halo concentration as input, which CHARM does not currently output. Instead, for now, we may want to just pull from a halo-concentration relation.

Important code bits:
- Where we apply the HOD: https://github.com/maho3/ltu-cmass/blob/f271aad72ef3ea52d723b48d87cff26538160320/cmass/bias/apply_hod.py#L69
- Where we construct the HOD model: https://github.com/maho3/ltu-cmass/blob/f271aad72ef3ea52d723b48d87cff26538160320/cmass/bias/tools/hod.py#L137

One could add another configuration to `build_HOD_model`. Or, if more functionality is needed, could redo `populate_hod` to take different inputs.

**Comment by christopherlovell** [comment]
As discussed on call today, these models require beyond halo mass features, such as concentration and environment, that may not readily available in the pipeline as it stands.

I have implemented some of the out-of-the-box HaloTools models, including Leauthaud+11 and Zu & Mandelbaum+15 on the new_hod_models branch (linked), but these need to be integrated into the `parse_hod` and `get_hod_params` methods in `apply_hod.py` in order to accept arbitrary HOD prescriptions and parametrisations
